services:
  app:
    build: .
    env_file:
      - .env
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:17.4-alpine3.21
    container_name: ${POSTGRES_CONTAINER_NAME}
    hostname: ${POSTGRES_HOSTNAME}
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - db_store:/var/lib/postgresql/data

volumes:
  db_store: